const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
const CHANGE_LOGIN_FORM_SHOW_STATE = 'CHANGE_LOGIN_FORM_SHOW_STATE';
const REFRESH_ACCOUNTS_LIST = 'REFRESH_ACCOUNTS_LIST';

export {
  SET_CURRENT_ACCOUNT,
  CHANGE_LOGIN_FORM_SHOW_STATE,
  REFRESH_ACCOUNTS_LIST,
};
